# Generated by Django 4.1.7 on 2023-03-04 07:08

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import products_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colors_app", "0001_initial"),
        ("sizes_app", "0001_initial"),
        ("categories_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_num_in_stock",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "subsubcategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="categories_app.subsubcategory",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color",
                        to="colors_app.color",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to="products_app.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductVariations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_in_stock",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock",
                        to="products_app.product",
                    ),
                ),
                (
                    "product_color",
                    models.ManyToManyField(
                        related_name="product_color", to="products_app.productcolor"
                    ),
                ),
                (
                    "size",
                    models.ManyToManyField(related_name="size", to="sizes_app.size"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products_app.models.product_image_location,
                    ),
                ),
                (
                    "productColor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_color_images",
                        to="products_app.productcolor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="product_name"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="price"
                    ),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="products_app.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product Translation",
                "db_table": "products_app_product_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
