# Generated by Django 4.1.7 on 2023-03-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products_app", "0002_alter_productvariations_product_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productvariations",
            old_name="product_color",
            new_name="product_color_variations",
        ),
    ]
