# Generated by Django 4.1.7 on 2023-03-06 08:29

from django.db import migrations, models
import django.db.models.deletion
import products_app.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products_app",
            "0003_rename_product_color_productvariations_product_color_variations",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductThumbnailImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=products_app.models.product_thumbnail_image_location,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thumbnail",
                        to="products_app.product",
                    ),
                ),
            ],
        ),
    ]
