# Generated by Django 4.1.7 on 2023-03-08 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("colors_app", "0001_initial"),
        ("products_app", "0005_alter_productcolor_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcolor",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="color",
                to="colors_app.color",
            ),
        ),
    ]
