# Generated by Django 4.1.7 on 2023-03-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color_name", models.CharField(max_length=15, unique=True)),
                ("hex_color", models.CharField(max_length=7, unique=True)),
            ],
        ),
    ]
